# Generated by Django 5.2 on 2025-05-08 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_tasks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='proyect',
            new_name='project',
        ),
    ]
