# Generated by Django 5.2 on 2025-05-20 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_task_donde'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='donde',
            new_name='done',
        ),
    ]
